---
title: "3.1a Quality control of WGS data"
format:
  html:
    theme: yeti
---

Lectures (2 total) Lecture 1: Quality control of raw Illumina reads Lecture 2: Illumina read trimming and adapter clipping. Note: in a previous version of the course, we used Trimmomatic to trim Illumina reads (which is why it's mentioned in the lectures). However, in your Hands-on activity, you will use fastp. Both tools are similar/accomplish virtually the same thing...fastp is just WAY faster, which is why we'll be using it here\! Practical readings (3 total) FastQC's official help pages (not pretty, but very useful; click on the links within the directories to read about each analysis/component of FastQC): https://www.bioinformatics.babraham.ac.uk/projects/fastqc/Help  FastQC explained (focuses on RNA-seq, but still relevant\! Much nicer to read/look at compared to the official FastQC help pages): https://hbctraining.github.io/Intro-to-rnaseq-hpc-salmon/lessons/qc\_fastqc\_assessment.html  FastQC results explained...with fun, pretty pictures\! You only need to read the section titled "FastQC" (focuses on analysis on ancient DNA, but does a great job explaining FastQC output and how to interpret it\!): https://nf-co.re/eager/2.1.0/docs/output  Supplemental readings (optional; 1 total) If you're interested in the very technical, nitty-gritty details of read trimming and filtering, check out the fastp paper: Chen, et al. 2018. fastp: an ultra-fast all-in-one FASTQ preprocessor. URL: https://academic.oup.com/bioinformatics/article/34/17/i884/5093234  Hands-on exercises (1 total) Hands-on exercise 3.1a: QC queen 👑 To complete the activity, go to the following URL (you can also download the HTML file and open it in your favorite browser): 3\_1\_activity\_command\_line\_intro\_v2\_fastp\_hpc2n.html If, for some reason, the HTML doesn't work in your browser, a print-out of the activity can be found here: 3\_1\_activity\_command\_line\_intro\_v2\_fastp\_hpc2n.pdf
